import { Check, Clock3, FileWarning, LayoutDashboard, Loader2, MessageCircle, ShieldAlert, Users, X } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { ADMIN_EMAIL } from "@shared/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import SiteShell from "@/components/SiteShell";
import { toast } from "sonner";

export default function AdminDashboard() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin" || user?.email === ADMIN_EMAIL;
  const stats = trpc.admin.stats.useQuery(undefined, { enabled: isAdmin });
  const pending = trpc.admin.pendingListings.useQuery(undefined, { enabled: isAdmin });
  const utils = trpc.useUtils();
  const moderate = trpc.admin.moderateListing.useMutation({ onSuccess: (_, input) => { toast.success(input.decision === "approved" ? "Listing published" : "Listing rejected"); utils.admin.stats.invalidate(); utils.admin.pendingListings.invalidate(); }, onError: error => toast.error(error.message) });
  if (loading) return <SiteShell><div className="shell py-24 text-center"><Loader2 className="mx-auto animate-spin" /></div></SiteShell>;
  if (!user || !isAdmin) return <SiteShell><div className="shell py-24"><div className="auth-card"><span className="brand-mark mx-auto"><ShieldAlert size={20} /></span><h1 className="mt-5 font-display text-3xl font-semibold">Admin access only.</h1><p className="mt-3 text-sm leading-6 text-[#718780]">This area is protected by server-side role checks.</p><Link href="/" className="text-link mt-6 inline-flex">Return home</Link></div></div></SiteShell>;
  const cards = [{ label: "Total users", value: stats.data?.users ?? 0, icon: Users, color: "mint" }, { label: "All listings", value: stats.data?.listings ?? 0, icon: LayoutDashboard, color: "sky" }, { label: "Pending review", value: stats.data?.pendingListings ?? 0, icon: Clock3, color: "sand" }, { label: "Open reports", value: stats.data?.reports ?? 0, icon: FileWarning, color: "coral" }, { label: "Messages", value: stats.data?.messages ?? 0, icon: MessageCircle, color: "mint" }];
  return <SiteShell><section className="shell admin-shell"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Admin console / لوحة الإدارة</p><h1 className="page-title mt-3">Keep the flock<br /><em>healthy.</em></h1><p className="page-lede">A calm view of the marketplace’s trust signals and review queue.</p></div><span className="admin-badge"><ShieldAlert size={15} /> Protected admin · {user.email}</span></div><div className="stats-grid mt-10">{cards.map(card => <div key={card.label} className={`admin-stat admin-stat-${card.color}`}><card.icon size={19} /><p>{card.label}</p><strong>{card.value}</strong></div>)}</div><div className="mt-12 flex items-end justify-between gap-4"><div><p className="eyebrow">Moderation queue / قائمة المراجعة</p><h2 className="section-title mt-2 text-3xl">Listings waiting<br /><em>for a human.</em></h2></div><Link href="/marketplace" className="text-link">View public marketplace →</Link></div><div className="mt-6 overflow-hidden rounded-2xl border border-[#dce7df] bg-white">{pending.isLoading ? <div className="p-10 text-center"><Loader2 className="mx-auto animate-spin" /></div> : pending.data?.length ? <div className="divide-y divide-[#edf1ed]">{pending.data.map(item => <article key={item.id} className="admin-row"><div className="admin-row-image">{item.coverImage ? <img src={item.coverImage} alt={item.titleEn} /> : <span>🦜</span>}</div><div className="min-w-0 flex-1"><h3 className="truncate font-display text-lg font-semibold text-[#183b39]">{item.titleEn}</h3><p className="mt-1 text-sm text-[#7f938d]">{item.sellerName || "Unknown seller"} · {item.sellerEmail || "No email"} · {item.location}</p><p className="mt-2 text-xs text-[#9aa9a3]">Submitted {new Date(item.createdAt).toLocaleString()} · {Number(item.price).toLocaleString("en-EG")} EGP</p></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="icon" className="rounded-full border-[#e6c7c0] text-[#bd5941]" onClick={() => moderate.mutate({ listingId: item.id, decision: "rejected" })} disabled={moderate.isPending} aria-label="Reject listing"><X size={16} /></Button><Button size="icon" className="rounded-full bg-[#183b39] text-white hover:bg-[#2e5b55]" onClick={() => moderate.mutate({ listingId: item.id, decision: "approved" })} disabled={moderate.isPending} aria-label="Approve listing"><Check size={16} /></Button></div></article>)}</div> : <div className="empty-state m-5"><Check size={30} /><h3 className="font-display text-lg font-semibold">The queue is clear.</h3><p>New submissions will appear here for human review.</p></div>}</div></section></SiteShell>;
}
