import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Image as ImageIcon, Loader2, Plus, XCircle } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import SiteShell from "@/components/SiteShell";

export default function MyListings() {
  const { isAuthenticated, loading } = useAuth();
  const mine = trpc.listings.mine.useQuery(undefined, { enabled: isAuthenticated });
  const reorder = trpc.listings.reorderImages.useMutation({ onSuccess: () => { toast.success("Image order saved"); mine.refetch(); }, onError: error => toast.error(error.message) });
  if (loading || (isAuthenticated && mine.isLoading)) return <SiteShell><div className="shell py-24 text-center"><Loader2 className="mx-auto animate-spin" /></div></SiteShell>;
  if (!isAuthenticated) return <SiteShell><div className="shell py-24"><div className="auth-card"><span className="brand-mark mx-auto"><ImageIcon size={20} /></span><h1 className="mt-5 font-display text-3xl font-semibold">Your listings, in one calm place.</h1><Button className="cta-primary mt-7" onClick={() => startLogin()}>Log in securely</Button></div></div></SiteShell>;
  const move = (listing: NonNullable<typeof mine.data>[number], index: number, direction: -1 | 1) => { const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= listing.images.length) return; const ids = listing.images.map(image => image.id); [ids[index], ids[nextIndex]] = [ids[nextIndex], ids[index]]; reorder.mutate({ listingId: listing.id, imageIds: ids }); };
  return <SiteShell><section className="shell py-10 sm:py-16"><Link href="/profile" className="back-link"><ArrowLeft size={16} /> Back to profile</Link><div className="mt-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Seller studio / إعلاناتي</p><h1 className="page-title mt-3">Make every photo<br /><em>work harder.</em></h1><p className="page-lede">Move any image left or right; the first image becomes the cover.</p></div><Link href="/sell" className="cta-primary inline-flex"><Plus size={16} /> New listing</Link></div><div className="mt-10 space-y-5">{mine.data?.length ? mine.data.map(listing => <article key={listing.id} className="listing-manager-card"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold text-[#183b39]">{listing.titleEn}</h2><p className="mt-1 text-xs text-[#849690]">{listing.moderationStatus === "approved" ? "Live" : listing.moderationStatus === "rejected" ? "Needs an update" : "Waiting for review"} · {new Date(listing.createdAt).toLocaleDateString()}</p></div><span className={`status-chip status-${listing.moderationStatus}`}>{listing.moderationStatus === "approved" ? <CheckCircle2 size={14} /> : listing.moderationStatus === "rejected" ? <XCircle size={14} /> : <Clock3 size={14} />}{listing.moderationStatus}</span></div>{listing.images.length ? <div className="manager-images">{listing.images.map((image, index) => <div key={image.id} className={`manager-image ${image.isCover ? "manager-image-cover" : ""}`}><img src={image.storagePath} alt={`${listing.titleEn} photo ${index + 1}`} />{image.isCover && <span>Cover</span>}<div className="manager-image-controls">{index > 0 && <button type="button" onClick={() => move(listing, index, -1)} aria-label="Move image left"><ArrowLeft size={12} /></button>}{index < listing.images.length - 1 && <button type="button" onClick={() => move(listing, index, 1)} aria-label="Move image right"><ArrowRight size={12} /></button>}</div></div>)}</div> : <div className="manager-empty"><ImageIcon size={17} /> Add photos from a new listing to build trust.</div>}</article>) : <div className="empty-state"><ImageIcon size={30} /><h2 className="font-display text-xl font-semibold">No listings yet.</h2><p>Start with a clear cover photo and a kind description.</p><Link href="/sell" className="text-link">Create your first listing →</Link></div>}</div></section></SiteShell>;
}
