import { useEffect, useState } from "react";
import { ArrowLeft, Edit3, Eye, Loader2, Plus, Trash2 } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import SiteShell from "@/components/SiteShell";
import { toast } from "sonner";

type Listing = { id: number; titleEn: string; price: string; location: string; status: string; moderationStatus: string; images: Array<{ id: number; storagePath: string }> };
const statusLabel: Record<string, string> = { published: "منشور", pending_review: "قيد المراجعة", archived: "مؤرشف", sold: "تم البيع", reserved: "محجوز" };

export default function MyListings() {
  const { isAuthenticated, loading } = useAuth(); const [, navigate] = useLocation(); const [items, setItems] = useState<Listing[]>([]); const [busy, setBusy] = useState<number | null>(null);
  const load = async () => { const response = await fetch("/api/listings/mine"); if (!response.ok) throw new Error("تعذر تحميل إعلاناتك"); setItems(await response.json()); };
  useEffect(() => { if (isAuthenticated) load().catch(error => toast.error(error.message)); }, [isAuthenticated]);
  const remove = async (id: number) => { if (!window.confirm("هل تريد حذف هذا الإعلان نهائيًا؟ / Delete this listing permanently?")) return; setBusy(id); try { const response = await fetch(`/api/listings/${id}`, { method: "DELETE" }); if (!response.ok) throw new Error("تعذر حذف الإعلان"); setItems(current => current.filter(item => item.id !== id)); toast.success("تم حذف الإعلان"); } catch (error) { toast.error(error instanceof Error ? error.message : "حدث خطأ"); } finally { setBusy(null); } };
  if (loading || (isAuthenticated && !items && false)) return <SiteShell><div className="shell py-24 text-center"><Loader2 className="mx-auto animate-spin" /></div></SiteShell>;
  if (!isAuthenticated) return <SiteShell><div className="shell py-24"><div className="auth-card"><h1 className="font-display text-3xl font-semibold">إعلاناتك في مكان واحد</h1><p className="mt-3 text-sm text-[#718780]">سجّل الدخول لإدارة إعلاناتك.</p><Button className="cta-primary mt-6" onClick={() => startLogin()}>تسجيل الدخول</Button></div></div></SiteShell>;
  return <SiteShell><section className="shell py-10 sm:py-16"><Link href="/profile" className="back-link"><ArrowLeft size={16} /> العودة للملف الشخصي</Link><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">My listings / إعلاناتي</p><h1 className="page-title">إعلاناتك،<br /><em>بإدارتك.</em></h1><p className="page-lede">عدّل إعلانك أو احذفه وقتما شئت. التعديلات تعود للمراجعة قبل النشر.</p></div><Button className="cta-primary" onClick={() => navigate("/sell")}><Plus size={16} /> إضافة إعلان</Button></div>{items.length ? <div className="mt-10 grid gap-4 md:grid-cols-2">{items.map(item => <article key={item.id} className="listing-card overflow-hidden"><div className="flex gap-4 p-4">{item.images[0] ? <img src={item.images[0].storagePath} alt={item.titleEn} className="size-24 rounded-2xl object-cover" /> : <div className="size-24 rounded-2xl bg-[#eef5ed]" />}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="truncate font-display text-xl font-semibold text-[#183b39]">{item.titleEn}</h2><span className="rounded-full bg-[#eef5ed] px-2 py-1 text-[10px] font-bold text-[#557b69]">{statusLabel[item.status] || item.status}</span></div><p className="mt-2 text-sm text-[#718780]">{Number(item.price).toLocaleString("en-EG")} EGP · {item.location}</p></div></div><div className="flex flex-wrap gap-2 border-t border-[#e7eee7] p-3"><Button variant="outline" size="sm" onClick={() => navigate(`/listing/${item.id}`)}><Eye size={15} /> عرض</Button><Button variant="outline" size="sm" onClick={() => navigate(`/listing/${item.id}/edit`)}><Edit3 size={15} /> تعديل</Button><Button variant="outline" size="sm" className="text-[#bd5941]" disabled={busy === item.id} onClick={() => remove(item.id)}>{busy === item.id ? <Loader2 size={15} className="animate-spin" /> : <Trash2 size={15} />} حذف</Button></div></article>)}</div> : <div className="empty-state mt-10"><p>لا توجد إعلانات بعد.</p><Button className="cta-primary mt-4" onClick={() => navigate("/sell")}>أنشئ أول إعلان</Button></div>}</section></SiteShell>;
}
